In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

In [11]:
BASE = "/Users/dhruvjani/2026projects/micromobility-safety-deprivation-uk/dataset/"

collisions = pd.read_csv(BASE + "dft-road-casualty-statistics-collision-last-5-years.csv", low_memory=False)
casualties = pd.read_csv(BASE + "dft-road-casualty-statistics-casualty-last-5-years.csv", low_memory=False)
vehicles   = pd.read_csv(BASE + "dft-road-casualty-statistics-vehicle-last-5-years.csv",  low_memory=False)

print(f"Collisions : {len(collisions):,} rows, {collisions.shape[1]} columns")
print(f"Casualties : {len(casualties):,} rows, {casualties.shape[1]} columns")
print(f"Vehicles   : {len(vehicles):,} rows, {vehicles.shape[1]} columns")

Collisions : 503,475 rows, 44 columns
Casualties : 640,522 rows, 23 columns
Vehicles   : 920,692 rows, 32 columns

In [20]:
# ── COLLISIONS ──────────────────────────────────────────────────────────────

print("COLLISIONS DATASET")
print(f"Rows: {len(collisions):,}")
print(f"Columns: {collisions.shape[1]}")
print("\nFirst 5 Rows")
display(collisions.head())
print("\nData Types")
print(collisions.dtypes)
print("\nMissing Values")
missing_col = collisions.isnull().sum()
print(missing_col[missing_col > 0])
print("\nBasic Statistics")
display(collisions.describe())
print("\nYears Present")
print(collisions['collision_year'].value_counts().sort_index())


# ── CASUALTIES ──────────────────────────────────────────────────────────────

print("\n\nCASUALTIES DATASET")
print(f"Rows: {len(casualties):,}")
print(f"Columns: {casualties.shape[1]}")
print("\nFirst 5 Rows")
display(casualties.head())
print("\nData Types")
print(casualties.dtypes)
print("\nMissing Values")
missing_cas = casualties.isnull().sum()
print(missing_cas[missing_cas > 0])
print("\nBasic Statistics")
display(casualties.describe())
print("\nCasualty Type Breakdown")
print(casualties['casualty_type'].value_counts().sort_index())


# ── VEHICLES ────────────────────────────────────────────────────────────────

print("\n\nVEHICLES DATASET")
print(f"Rows: {len(vehicles):,}")
print(f"Columns: {vehicles.shape[1]}")
print("\nFirst 5 Rows")
display(vehicles.head())
print("\nData Types")
print(vehicles.dtypes)
print("\nMissing Values")
missing_veh = vehicles.isnull().sum()
print(missing_veh[missing_veh > 0])
print("\nBasic Statistics")
display(vehicles.describe())
print("\nVehicle Type Breakdown")
print(vehicles['vehicle_type'].value_counts().sort_index())

COLLISIONS DATASET
Rows: 503,475
Columns: 44

First 5 Rows

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,date,day_of_week,time,local_authority_district,local_authority_ons_district,local_authority_highway,local_authority_highway_current,first_road_class,first_road_number,road_type,speed_limit,junction_detail_historic,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing_human_control_historic,pedestrian_crossing_physical_facilities_historic,pedestrian_crossing,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,2021170H10421,2021,170H10421,447098.00,532997.00,-1.27,54.69,17,3,2,2,22/05/2021,7,22:44,-1,E06000001,E06000001,E06000001,6,0,6,60,0,0,-1,0,-1,0,0,0,6,1,1,0,0,0,2,1,2,E01011959,-1,0,0.29,0.71
1,2021170H11231,2021,170H11231,450486.00,533118.00,-1.22,54.69,17,3,2,1,20/10/2021,4,15:50,-1,E06000001,E06000001,E06000001,4,1277,6,30,6,16,2,5,0,0,0,0,1,1,1,0,0,0,1,2,2,E01011973,-1,0,0.02,0.98
2,2020170M11750,2020,170M11750,449694.00,519733.00,-1.23,54.57,17,3,2,1,01/12/2020,3,18:00,243,E06000002,E06000002,E06000002,6,0,6,20,6,16,4,6,0,0,0,0,4,1,1,0,0,0,1,1,2,E01012092,-1,0,0.13,0.87
3,2021170M31761,2021,170M31761,449744.00,514217.00,-1.23,54.52,17,3,1,1,09/12/2021,5,16:55,-1,E06000002,E06000002,E06000002,5,0,6,40,0,0,-1,0,-1,0,0,0,4,1,2,0,0,0,2,1,2,E01032553,-1,0,0.18,0.82
4,2021170S10441,2021,170S10441,445971.00,520834.00,-1.29,54.58,17,3,3,1,12/04/2021,2,09:02,-1,E06000004,E06000004,E06000004,3,19,3,70,0,0,-1,0,-1,0,0,0,1,1,1,4,0,13,2,1,1,E01012258,-1,0,0.02,0.98

Data Types
collision_index                                      object
collision_year                                        int64
collision_ref_no                                     object
location_easting_osgr                               float64
location_northing_osgr                              float64
longitude                                           float64
latitude                                            float64
police_force                                          int64
collision_severity                                    int64
number_of_vehicles                                    int64
number_of_casualties                                  int64
date                                                 object
day_of_week                                           int64
time                                                 object
local_authority_district                              int64
local_authority_ons_district                         object
local_authority_highway                              object
local_authority_highway_current                      object
first_road_class                                      int64
first_road_number                                     int64
road_type                                             int64
speed_limit                                           int64
junction_detail_historic                              int64
junction_detail                                       int64
junction_control                                      int64
second_road_class                                     int64
second_road_number                                    int64
pedestrian_crossing_human_control_historic            int64
pedestrian_crossing_physical_facilities_historic      int64
pedestrian_crossing                                   int64
light_conditions                                      int64
weather_conditions                                    int64
road_surface_conditions                               int64
special_conditions_at_site                            int64
carriageway_hazards_historic                          int64
carriageway_hazards                                   int64
urban_or_rural_area                                   int64
did_police_officer_attend_scene_of_accident           int64
trunk_road_flag                                       int64
lsoa_of_accident_location                            object
enhanced_severity_collision                           int64
collision_injury_based                                int64
collision_adjusted_severity_serious                 float64
collision_adjusted_severity_slight                  float64
dtype: object

Missing Values
location_easting_osgr              65
location_northing_osgr             65
longitude                          65
latitude                           65
local_authority_highway_current    80
dtype: int64

Basic Statistics

,collision_year,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,day_of_week,local_authority_district,first_road_class,first_road_number,road_type,speed_limit,junction_detail_historic,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing_human_control_historic,pedestrian_crossing_physical_facilities_historic,pedestrian_crossing,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
count,503475.00,503410.00,503410.00,503410.00,503410.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00,503475.00
mean,2022.04,455410.09,274918.33,-1.20,52.36,27.51,2.75,1.83,1.27,4.14,55.73,4.22,788.15,5.26,35.99,3.88,6.81,1.75,3.25,226.25,0.27,1.00,5.91,2.02,1.67,1.38,0.17,0.12,2.48,1.32,1.48,1.72,1.52,0.52,0.24,0.75
std,1.39,92797.77,146044.46,1.36,1.32,24.30,0.47,0.69,0.70,1.94,161.72,1.46,1580.82,1.70,14.23,13.64,7.52,2.53,2.77,938.73,1.86,2.50,17.09,1.71,1.86,1.03,1.54,1.43,13.65,0.47,0.76,0.79,2.68,0.50,0.41,0.42
min,2020.00,65947.00,10211.00,-7.50,49.91,1.00,1.00,1.00,1.00,1.00,-1.00,1.00,0.00,1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,0.00,0.00,0.00
25%,2021.00,392836.25,175000.00,-2.11,51.46,4.00,3.00,1.00,1.00,2.00,-1.00,3.00,0.00,6.00,30.00,0.00,0.00,-1.00,0.00,-1.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,0.00,0.00,1.00,1.00,2.00,-1.00,0.00,0.00,0.81
50%,2022.00,461820.50,214357.00,-1.09,51.81,22.00,3.00,2.00,1.00,4.00,-1.00,4.00,32.00,6.00,30.00,1.00,0.00,2.00,4.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,0.00,0.00,1.00,1.00,2.00,3.00,1.00,0.00,1.00
75%,2023.00,529754.00,381859.00,-0.13,53.33,45.00,3.00,2.00,1.00,6.00,-1.00,6.00,534.00,6.00,40.00,3.00,13.00,4.00,6.00,0.00,0.00,0.00,0.00,4.00,1.00,2.00,0.00,0.00,0.00,2.00,2.00,2.00,3.00,1.00,0.16,1.00
max,2024.00,655345.00,1184351.00,1.76,60.54,99.00,3.00,26.00,70.00,7.00,941.00,6.00,9999.00,9.00,70.00,99.00,99.00,9.00,6.00,9999.00,9.00,9.00,99.00,7.00,9.00,9.00,9.00,9.00,99.00,3.00,3.00,2.00,7.00,1.00,1.00,1.00

Years Present
collision_year
2020     91199
2021    101087
2022    106004
2023    104258
2024    100927
Name: count, dtype: int64


CASUALTIES DATASET
Rows: 640,522
Columns: 23

First 5 Rows

,collision_index,collision_year,collision_ref_no,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_imd_decile,lsoa_of_casualty,enhanced_casualty_severity,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding
0,2020010280094,2020,010280094,1,1,3,2,24,5,3,8,9,0,0,0,0,3,E01003536,-1,0,0.00,1.00,-1
1,202031D109620,2020,31D109620,1,1,3,2,95,11,2,5,1,0,0,0,0,6,E01028156,-1,0,1.00,0.00,-1
2,2020401003715,2020,401003715,1,1,3,1,39,7,3,5,1,0,0,0,0,2,E01017492,3,1,0.00,1.00,-1
3,2021201086330,2021,201086330,1,1,3,1,63,9,3,6,9,0,0,2,0,3,E01009140,3,1,0.00,1.00,-1
4,2021371050963,2021,371050963,1,1,3,1,51,8,3,9,9,0,0,0,0,9,E01030190,3,1,0.00,1.00,-1

Data Types
collision_index                        object
collision_year                          int64
collision_ref_no                       object
vehicle_reference                       int64
casualty_reference                      int64
casualty_class                          int64
sex_of_casualty                         int64
age_of_casualty                         int64
age_band_of_casualty                    int64
casualty_severity                       int64
pedestrian_location                     int64
pedestrian_movement                     int64
car_passenger                           int64
bus_or_coach_passenger                  int64
pedestrian_road_maintenance_worker      int64
casualty_type                           int64
casualty_imd_decile                     int64
lsoa_of_casualty                       object
enhanced_casualty_severity              int64
casualty_injury_based                   int64
casualty_adjusted_severity_serious    float64
casualty_adjusted_severity_slight     float64
casualty_distance_banding               int64
dtype: object

Missing Values
Series([], dtype: int64)

Basic Statistics

,collision_year,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_imd_decile,enhanced_casualty_severity,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding
count,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00,640522.00
mean,2022.05,1.45,1.35,1.47,1.36,36.92,6.32,2.79,0.77,0.62,0.23,0.05,0.00,7.10,4.29,1.71,0.58,0.21,0.78,-0.50
std,1.39,2.54,2.61,0.73,0.54,19.60,2.46,0.44,2.16,1.98,0.62,0.43,0.26,8.72,3.22,2.58,0.49,0.39,0.40,1.21
min,2020.00,1.00,1.00,1.00,-1.00,-1.00,-1.00,1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,0.00,0.00,0.00,-1.00
25%,2021.00,1.00,1.00,1.00,1.00,22.00,5.00,3.00,0.00,0.00,0.00,0.00,0.00,1.00,2.00,-1.00,0.00,0.00,0.89,-1.00
50%,2022.00,1.00,1.00,1.00,1.00,34.00,6.00,3.00,0.00,0.00,0.00,0.00,0.00,9.00,4.00,3.00,1.00,0.00,1.00,-1.00
75%,2023.00,2.00,1.00,2.00,2.00,51.00,8.00,3.00,0.00,0.00,0.00,0.00,0.00,9.00,7.00,3.00,1.00,0.10,1.00,-1.00
max,2024.00,999.00,999.00,3.00,9.00,101.00,11.00,3.00,10.00,9.00,9.00,9.00,2.00,99.00,10.00,7.00,1.00,1.00,1.00,5.00

Casualty Type Breakdown
casualty_type
-1       4935
 0      89170
 1      77993
 2       4666
 3      41513
 4       8944
 5      21337
 8       7270
 9     344170
 10       864
 11     10035
 16       362
 17       367
 18        29
 19     18439
 20      1081
 21      2306
 22      1223
 23      1190
 90      2307
 97      1673
 98       630
 99        18
Name: count, dtype: int64


VEHICLES DATASET
Rows: 920,692
Columns: 32

First 5 Rows

,collision_index,collision_year,collision_ref_no,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre_historic,vehicle_manoeuvre,vehicle_direction_from,vehicle_direction_to,vehicle_location_restricted_lane_historic,vehicle_location_restricted_lane,junction_location,skidding_and_overturning,hit_object_in_carriageway,vehicle_leaving_carriageway,hit_object_off_carriageway,first_point_of_impact,vehicle_left_hand_drive,journey_purpose_of_driver_historic,journey_purpose_of_driver,sex_of_driver,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,lsoa_of_driver,escooter_flag,driver_distance_banding
0,2020210979534,2020,210979534,2,5,0,3,3,4,6,0,0,0,0,0,0,0,2,1,5,6,1,57,9,798,1,4,BMW F 800,3,E01010422,0,-1
1,2020030959800,2020,030959800,1,5,0,17,19,2,6,0,0,0,0,0,1,0,1,1,6,6,1,59,9,798,1,3,BMW F 800,6,E01025351,0,-1
2,2020360978858,2020,360978858,2,5,0,18,19,8,4,0,0,0,5,0,0,0,1,1,2,2,1,64,9,798,1,11,BMW F 800,4,E01026874,0,-1
3,2020430340711,2020,430340711,1,5,0,18,19,3,7,0,0,0,0,0,7,4,1,1,6,6,1,48,8,798,1,8,BMW F 800,8,E01017758,0,-1
4,2020010260297,2020,010260297,1,5,0,99,99,9,9,99,99,0,9,99,9,99,9,1,2,2,1,36,7,798,1,9,BMW F 800,8,E01016121,0,-1

Data Types
collision_index                              object
collision_year                                int64
collision_ref_no                             object
vehicle_reference                             int64
vehicle_type                                  int64
towing_and_articulation                       int64
vehicle_manoeuvre_historic                    int64
vehicle_manoeuvre                             int64
vehicle_direction_from                        int64
vehicle_direction_to                          int64
vehicle_location_restricted_lane_historic     int64
vehicle_location_restricted_lane              int64
junction_location                             int64
skidding_and_overturning                      int64
hit_object_in_carriageway                     int64
vehicle_leaving_carriageway                   int64
hit_object_off_carriageway                    int64
first_point_of_impact                         int64
vehicle_left_hand_drive                       int64
journey_purpose_of_driver_historic            int64
journey_purpose_of_driver                     int64
sex_of_driver                                 int64
age_of_driver                                 int64
age_band_of_driver                            int64
engine_capacity_cc                            int64
propulsion_code                               int64
age_of_vehicle                                int64
generic_make_model                           object
driver_imd_decile                             int64
lsoa_of_driver                               object
escooter_flag                                 int64
driver_distance_banding                       int64
dtype: object

Missing Values
Series([], dtype: int64)

Basic Statistics

,collision_year,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre_historic,vehicle_manoeuvre,vehicle_direction_from,vehicle_direction_to,vehicle_location_restricted_lane_historic,vehicle_location_restricted_lane,junction_location,skidding_and_overturning,hit_object_in_carriageway,vehicle_leaving_carriageway,hit_object_off_carriageway,first_point_of_impact,vehicle_left_hand_drive,journey_purpose_of_driver_historic,journey_purpose_of_driver,sex_of_driver,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,driver_imd_decile,escooter_flag,driver_distance_banding
count,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00,920692.00
mean,2022.04,1.55,9.84,0.23,18.11,20.34,4.37,4.42,7.93,8.11,2.62,0.95,8.41,1.04,8.34,2.02,1.58,4.03,5.01,1.49,34.68,5.76,1335.07,1.15,6.22,3.81,0.01,-0.54
std,1.39,2.56,10.86,1.39,25.02,24.27,2.77,2.76,26.78,26.81,3.32,2.56,27.02,2.69,26.84,1.83,2.07,2.58,2.12,0.72,21.44,3.28,1566.71,1.87,6.51,3.49,0.08,1.19
min,2020.00,1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00,0.00,-1.00
25%,2021.00,1.00,9.00,0.00,4.00,7.00,2.00,2.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,2.00,6.00,1.00,22.00,5.00,-1.00,1.00,0.00,1.00,0.00,-1.00
50%,2022.00,1.00,9.00,0.00,17.00,19.00,5.00,5.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,1.00,1.00,6.00,6.00,1.00,34.00,6.00,1364.00,1.00,5.00,4.00,0.00,-1.00
75%,2023.00,2.00,9.00,0.00,18.00,19.00,7.00,7.00,0.00,0.00,6.00,0.00,0.00,0.00,0.00,3.00,1.00,6.00,6.00,2.00,50.00,8.00,1896.00,2.00,11.00,7.00,0.00,-1.00
max,2024.00,999.00,99.00,9.00,99.00,99.00,9.00,9.00,99.00,99.00,9.00,9.00,99.00,9.00,99.00,9.00,9.00,6.00,9.00,3.00,101.00,11.00,48000.00,12.00,123.00,10.00,1.00,5.00

Vehicle Type Breakdown
vehicle_type
-1       6545
 1      81231
 2       5323
 3      44442
 4       9489
 5      21819
 8      14360
 9     628614
 10      1435
 11     14290
 16       379
 17      2015
 18        90
 19     58092
 20      4060
 21     13115
 22      1471
 23      1393
 90      5048
 97      2830
 98      4319
 99       332
Name: count, dtype: int64

In [12]:
print("COLLISIONS")
print(collisions.dtypes)
print("\nCASUALTIES")
print(casualties.dtypes)

COLLISIONS
collision_index                                      object
collision_year                                        int64
collision_ref_no                                     object
location_easting_osgr                               float64
location_northing_osgr                              float64
longitude                                           float64
latitude                                            float64
police_force                                          int64
collision_severity                                    int64
number_of_vehicles                                    int64
number_of_casualties                                  int64
date                                                 object
day_of_week                                           int64
time                                                 object
local_authority_district                              int64
local_authority_ons_district                         object
local_authority_highway                              object
local_authority_highway_current                      object
first_road_class                                      int64
first_road_number                                     int64
road_type                                             int64
speed_limit                                           int64
junction_detail_historic                              int64
junction_detail                                       int64
junction_control                                      int64
second_road_class                                     int64
second_road_number                                    int64
pedestrian_crossing_human_control_historic            int64
pedestrian_crossing_physical_facilities_historic      int64
pedestrian_crossing                                   int64
light_conditions                                      int64
weather_conditions                                    int64
road_surface_conditions                               int64
special_conditions_at_site                            int64
carriageway_hazards_historic                          int64
carriageway_hazards                                   int64
urban_or_rural_area                                   int64
did_police_officer_attend_scene_of_accident           int64
trunk_road_flag                                       int64
lsoa_of_accident_location                            object
enhanced_severity_collision                           int64
collision_injury_based                                int64
collision_adjusted_severity_serious                 float64
collision_adjusted_severity_slight                  float64
dtype: object

CASUALTIES
collision_index                        object
collision_year                          int64
collision_ref_no                       object
vehicle_reference                       int64
casualty_reference                      int64
casualty_class                          int64
sex_of_casualty                         int64
age_of_casualty                         int64
age_band_of_casualty                    int64
casualty_severity                       int64
pedestrian_location                     int64
pedestrian_movement                     int64
car_passenger                           int64
bus_or_coach_passenger                  int64
pedestrian_road_maintenance_worker      int64
casualty_type                           int64
casualty_imd_decile                     int64
lsoa_of_casualty                       object
enhanced_casualty_severity              int64
casualty_injury_based                   int64
casualty_adjusted_severity_serious    float64
casualty_adjusted_severity_slight     float64
casualty_distance_banding               int64
dtype: object

In [13]:
ped_cyc = casualties[casualties['casualty_type'].isin([0, 1])].copy()
ped_cyc['casualty_type_label'] = ped_cyc['casualty_type'].map({0: 'Pedestrian', 1: 'Cyclist'})

print(f"Pedestrian and cyclist casualties: {len(ped_cyc):,}")
print(ped_cyc['casualty_type_label'].value_counts())

Pedestrian and cyclist casualties: 167,163
casualty_type_label
Pedestrian    89170
Cyclist       77993
Name: count, dtype: int64

In [14]:
print("Years in dataset:")
print(collisions['collision_year'].value_counts().sort_index())

Years in dataset:
collision_year
2020     91199
2021    101087
2022    106004
2023    104258
2024    100927
Name: count, dtype: int64

In [15]:
cols_needed = [
    'collision_index', 'collision_year', 'collision_severity',
    'date', 'longitude', 'latitude',
    'urban_or_rural_area', 'local_authority_ons_district',
    'speed_limit', 'light_conditions', 'weather_conditions'
]

cols_needed = [c for c in cols_needed if c in collisions.columns]

merged = ped_cyc.merge(collisions[cols_needed], on='collision_index', how='left')
merged['severity_label'] = merged['collision_severity'].map({1: 'Fatal', 2: 'Serious', 3: 'Slight'})
merged['area_label']     = merged['urban_or_rural_area'].map({1: 'Urban', 2: 'Rural'})
merged = merged.dropna(subset=['longitude', 'latitude'])

print(f"Merged rows: {len(merged):,}")
print(merged['severity_label'].value_counts())

Merged rows: 167,141
severity_label
Slight     119161
Serious     45378
Fatal        2602
Name: count, dtype: int64

In [16]:
cols_needed = [
    'collision_index', 'collision_year', 'collision_severity',
    'date', 'longitude', 'latitude',
    'urban_or_rural_area', 'local_authority_ons_district',
    'speed_limit', 'light_conditions', 'weather_conditions'
]

cols_needed = [c for c in cols_needed if c in collisions.columns]
print("Columns found:", cols_needed)  # confirm collision_year is in there

merged = ped_cyc.merge(collisions[cols_needed], on='collision_index', how='left')
merged['severity_label'] = merged['collision_severity'].map({1: 'Fatal', 2: 'Serious', 3: 'Slight'})
merged['area_label']     = merged['urban_or_rural_area'].map({1: 'Urban', 2: 'Rural'})
merged = merged.dropna(subset=['longitude', 'latitude'])

print(f"Merged rows: {len(merged):,}")
print(merged['severity_label'].value_counts())

Columns found: ['collision_index', 'collision_year', 'collision_severity', 'date', 'longitude', 'latitude', 'urban_or_rural_area', 'local_authority_ons_district', 'speed_limit', 'light_conditions', 'weather_conditions']
Merged rows: 167,141
severity_label
Slight     119161
Serious     45378
Fatal        2602
Name: count, dtype: int64

In [17]:
print(merged.columns.tolist())

['collision_index', 'collision_year_x', 'collision_ref_no', 'vehicle_reference', 'casualty_reference', 'casualty_class', 'sex_of_casualty', 'age_of_casualty', 'age_band_of_casualty', 'casualty_severity', 'pedestrian_location', 'pedestrian_movement', 'car_passenger', 'bus_or_coach_passenger', 'pedestrian_road_maintenance_worker', 'casualty_type', 'casualty_imd_decile', 'lsoa_of_casualty', 'enhanced_casualty_severity', 'casualty_injury_based', 'casualty_adjusted_severity_serious', 'casualty_adjusted_severity_slight', 'casualty_distance_banding', 'casualty_type_label', 'collision_year_y', 'collision_severity', 'date', 'longitude', 'latitude', 'urban_or_rural_area', 'local_authority_ons_district', 'speed_limit', 'light_conditions', 'weather_conditions', 'severity_label', 'area_label']

In [18]:
urban = merged[merged['urban_or_rural_area'] == 1].copy()

# Use collision_year_y (from collisions table) or whichever exists
year_col = 'collision_year_y' if 'collision_year_y' in urban.columns else 'collision_year'

print(f"Urban pedestrian and cyclist casualties: {len(urban):,}")
print("\nBy year:")
print(urban[year_col].value_counts().sort_index())
print("\nBy casualty type:")
print(urban['casualty_type_label'].value_counts())

Urban pedestrian and cyclist casualties: 141,989

By year:
collision_year_y
2020    25562
2021    27937
2022    29952
2023    29369
2024    29169
Name: count, dtype: int64

By casualty type:
casualty_type_label
Pedestrian    77743
Cyclist       64246
Name: count, dtype: int64

In [21]:
ped_cyc = casualties[casualties['casualty_type'].isin([0, 1])].copy()
ped_cyc['casualty_type_label'] = ped_cyc['casualty_type'].map({0: 'Pedestrian', 1: 'Cyclist'})

print(f"Total pedestrian and cyclist casualties: {len(ped_cyc):,}")
print(ped_cyc['casualty_type_label'].value_counts())

Total pedestrian and cyclist casualties: 167,163
casualty_type_label
Pedestrian    89170
Cyclist       77993
Name: count, dtype: int64

In [22]:
collision_cols = [
    'collision_index', 'collision_year', 'collision_severity',
    'date', 'longitude', 'latitude',
    'urban_or_rural_area', 'local_authority_ons_district',
    'speed_limit', 'light_conditions', 'weather_conditions',
    'lsoa_of_accident_location'
]

collisions_slim = collisions[collision_cols].copy()

print(f"Collisions slim shape: {collisions_slim.shape}")
print(collisions_slim.head())

Collisions slim shape: (503475, 12)
  collision_index  collision_year  collision_severity        date  longitude  \
0   2021170H10421            2021                   3  22/05/2021      -1.27
1   2021170H11231            2021                   3  20/10/2021      -1.22
2   2020170M11750            2020                   3  01/12/2020      -1.23
3   2021170M31761            2021                   3  09/12/2021      -1.23
4   2021170S10441            2021                   3  12/04/2021      -1.29

   latitude  urban_or_rural_area local_authority_ons_district  speed_limit  \
0     54.69                    2                    E06000001           60
1     54.69                    1                    E06000001           30
2     54.57                    1                    E06000002           20
3     54.52                    2                    E06000002           40
4     54.58                    2                    E06000004           70

   light_conditions  weather_conditions lsoa_of_accident_location
0                 6                   1                 E01011959
1                 1                   1                 E01011973
2                 4                   1                 E01012092
3                 4                   1                 E01032553
4                 1                   1                 E01012258

In [23]:
escooter = vehicles.groupby('collision_index')['escooter_flag'].max().reset_index()

print(f"Escooter table shape: {escooter.shape}")
print(f"Collisions involving e-scooter: {escooter['escooter_flag'].sum():,}")
print(escooter['escooter_flag'].value_counts())

Escooter table shape: (503475, 2)
Collisions involving e-scooter: 5,827
escooter_flag
0    497648
1      5827
Name: count, dtype: int64

In [24]:
master = ped_cyc.merge(collisions_slim, on='collision_index', how='left')
master = master.merge(escooter, on='collision_index', how='left')

print(f"Master shape after merge: {master.shape}")
print(master.head())

Master shape after merge: (167163, 36)
  collision_index  collision_year_x collision_ref_no  vehicle_reference  \
0   2020010280094              2020        010280094                  1
1   202031D109620              2020        31D109620                  1
2   2020401003715              2020        401003715                  1
3   2021201086330              2021        201086330                  1
4   2021371050963              2021        371050963                  1

   casualty_reference  casualty_class  sex_of_casualty  age_of_casualty  \
0                   1               3                2               24
1                   1               3                2               95
2                   1               3                1               39
3                   1               3                1               63
4                   1               3                1               51

   age_band_of_casualty  casualty_severity  pedestrian_location  \
0                     5                  3                    8
1                    11                  2                    5
2                     7                  3                    5
3                     9                  3                    6
4                     8                  3                    9

   pedestrian_movement  car_passenger  bus_or_coach_passenger  \
0                    9              0                       0
1                    1              0                       0
2                    1              0                       0
3                    9              0                       0
4                    9              0                       0

   pedestrian_road_maintenance_worker  casualty_type  casualty_imd_decile  \
0                                   0              0                    3
1                                   0              0                    6
2                                   0              0                    2
3                                   2              0                    3
4                                   0              0                    9

  lsoa_of_casualty  enhanced_casualty_severity  casualty_injury_based  \
0        E01003536                          -1                      0
1        E01028156                          -1                      0
2        E01017492                           3                      1
3        E01009140                           3                      1
4        E01030190                           3                      1

   casualty_adjusted_severity_serious  casualty_adjusted_severity_slight  \
0                                0.00                               1.00
1                                1.00                               0.00
2                                0.00                               1.00
3                                0.00                               1.00
4                                0.00                               1.00

   casualty_distance_banding casualty_type_label  collision_year_y  \
0                         -1          Pedestrian              2020
1                         -1          Pedestrian              2020
2                         -1          Pedestrian              2020
3                         -1          Pedestrian              2021
4                         -1          Pedestrian              2021

   collision_severity        date  longitude  latitude  urban_or_rural_area  \
0                   3  14/11/2020       0.06     51.52                    1
1                   2  12/07/2020      -1.09     52.96                    1
2                   3  26/11/2020      -0.47     52.14                    1
3                   3  17/06/2021      -1.88     52.48                    1
4                   3  25/05/2021       1.27     52.07                    1

  local_authority_ons_district  speed_limit  light_conditions  \
0                    E09000025           30                 7
1                    E07000173           30                 1
2                    E06000055           30                 5
3                    E08000025           30                 4
4                    E07000244           20                 1

   weather_conditions lsoa_of_accident_location  escooter_flag
0                   2                 E01003538              0
1                   1                 E01028156              0
2                   7                 E01017466              0
3                   1                 E01009200              0
4                   1                 E01030190              0

In [25]:
master = master[master['urban_or_rural_area'] == 1].copy()

print(f"Urban only rows: {len(master):,}")
print(master['urban_or_rural_area'].value_counts())

Urban only rows: 141,989
urban_or_rural_area
1    141989
Name: count, dtype: int64

In [26]:
master.replace(-1, np.nan, inplace=True)
master = master.dropna(subset=['lsoa_of_accident_location', 'longitude', 'latitude'])

print(f"Rows after cleaning: {len(master):,}")
print(f"Rows dropped: {141989 - len(master):,}")

Rows after cleaning: 141,989
Rows dropped: 0

In [27]:
# Drop the duplicate year column from casualties side
master = master.drop(columns=['collision_year_x'])
master = master.rename(columns={'collision_year_y': 'collision_year'})

# Add readable labels
master['severity_label'] = master['collision_severity'].map({1: 'Fatal', 2: 'Serious', 3: 'Slight'})

print(f"Final master shape: {master.shape}")
print(f"\nBy year:")
print(master['collision_year'].value_counts().sort_index())
print(f"\nSeverity:")
print(master['severity_label'].value_counts())

Final master shape: (141989, 36)

By year:
collision_year
2020    25562
2021    27937
2022    29952
2023    29369
2024    29169
Name: count, dtype: int64

Severity:
severity_label
Slight     103350
Serious     37012
Fatal        1627
Name: count, dtype: int64

In [28]:
import os

os.makedirs("data/processed", exist_ok=True)

master.to_csv("data/processed/master_ped_cyc_urban_2020_2024.csv", index=False)

print("Saved successfully.")
print("Location: data/processed/master_ped_cyc_urban_2020_2024.csv")
print(f"Rows: {len(master):,}")
print(f"Columns: {master.shape[1]}")

Saved successfully.
Location: data/processed/master_ped_cyc_urban_2020_2024.csv
Rows: 141,989
Columns: 36

In [30]:

print("Sample LSOA codes in master:")
print(master['lsoa_of_accident_location'].head(10).tolist())

Sample LSOA codes in master:
['E01003538', 'E01028156', 'E01017466', 'E01009200', 'E01030190', 'E01033104', 'E01009007', 'E01028175', 'E01026597', 'E01014489']